### ISSUE TITLE
stop detecting other fields that have a simular callsign

### ISSUE THREAD

**Issue by bigjeff187** [iccowan/VATUSA_Base_ARTCC_Site#1]
https://github.com/iccowan/VATUSA_Base_ARTCC_Site/blob/02280e4fae2eb18326c6f3676aa19b8d6b24caa5/app/Console/Commands/OnlineControllerUpdate.php#L96

$facility + "_"

**Comment by iccowan** [comment]
Archiving. You're more than welcome to fork and fix this issue along with any other necessary updates.
